// Code generated by sqlc. DO NOT EDIT.

package pgsql

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createArticleStmt, err = db.PrepareContext(ctx, createArticle); err != nil {
		return nil, fmt.Errorf("error preparing query CreateArticle: %w", err)
	}
	if q.deleteArticleStmt, err = db.PrepareContext(ctx, deleteArticle); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteArticle: %w", err)
	}
	if q.getAllArticlesStmt, err = db.PrepareContext(ctx, getAllArticles); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllArticles: %w", err)
	}
	if q.getOneArticleByIdStmt, err = db.PrepareContext(ctx, getOneArticleById); err != nil {
		return nil, fmt.Errorf("error preparing query GetOneArticleById: %w", err)
	}
	if q.updateArticleStmt, err = db.PrepareContext(ctx, updateArticle); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateArticle: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createArticleStmt != nil {
		if cerr := q.createArticleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createArticleStmt: %w", cerr)
		}
	}
	if q.deleteArticleStmt != nil {
		if cerr := q.deleteArticleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteArticleStmt: %w", cerr)
		}
	}
	if q.getAllArticlesStmt != nil {
		if cerr := q.getAllArticlesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllArticlesStmt: %w", cerr)
		}
	}
	if q.getOneArticleByIdStmt != nil {
		if cerr := q.getOneArticleByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOneArticleByIdStmt: %w", cerr)
		}
	}
	if q.updateArticleStmt != nil {
		if cerr := q.updateArticleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateArticleStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                    DBTX
	tx                    *sql.Tx
	createArticleStmt     *sql.Stmt
	deleteArticleStmt     *sql.Stmt
	getAllArticlesStmt    *sql.Stmt
	getOneArticleByIdStmt *sql.Stmt
	updateArticleStmt     *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                    tx,
		tx:                    tx,
		createArticleStmt:     q.createArticleStmt,
		deleteArticleStmt:     q.deleteArticleStmt,
		getAllArticlesStmt:    q.getAllArticlesStmt,
		getOneArticleByIdStmt: q.getOneArticleByIdStmt,
		updateArticleStmt:     q.updateArticleStmt,
	}
}
