// Code generated by sqlc. DO NOT EDIT.

package pgsql

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Article struct {
	ID      uuid.UUID    `json:"id"`
	Title   string       `json:"title"`
	URL     string       `json:"url"`
	SavedOn time.Time    `json:"savedon"`
	ReadOn  sql.NullTime `json:"readon"`
}
