version: "3.4"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: tpassword
  frontend:
    build:
      dockerfile: ../ops/frontend/Dockerfile
      context: frontend
    volumes:
      - ./frontend:/app
    ports:
      - 8087:8087
      - 8007:8000
    env_file:
      - frontend/.env
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
  backend:
    build:
      dockerfile: ../ops/backend/Dockerfile
      context: backend
    ports:
      - 8888:8888
    volumes:
    - ./backend:/app